---
- hosts: localhost
  gather_facts: true
  vars:
    - sno_release: "{{ sno_version }}.{{ sno_minor_version }}"
    - sno_local_release: "{{ 'ocp/openshift' +  sno_release | replace('.','') }}"
    - sno_util_hostname: "{{ sno_util_host_prefix }}.{{ sno_domain_name }}"
    - sno_infraenv_name: "{{ sno_cluster_name }}-infraenv"
    - sno_hostname: "{{ sno_host_prefix }}.{{ sno_cluster_name }}.{{ sno_domain_name }}"
    
  roles:
    - validate_parms

  post_tasks:
    - name: Success message
      debug:
        msg: "Parameter validation successful"
