---
- name: Patch external Operator hub sources
  k8s_json_patch:
    api_version: config.openshift.io/v1
    kind: OperatorHub
    name: cluster
    kubeconfig: "{{ sno_cluster_name }}-kubeconfig"
    patch:
      - op: add
        path: /spec/disableAllDefaultSources
        value: true


